#!/bin/bash

echo "🔧 Script de configuration Xcode pour Mac mini"
echo "=============================================="
echo ""
echo "Exécutez ces commandes dans le terminal sur votre Mac mini :"
echo ""
echo "# 1. Nettoyer et recompiler le backend (si nécessaire)"
echo "cd TradingSystem/Backend"
echo "rm -rf build && mkdir build && cd build"
echo "cmake .. && make"
echo ""
echo "# 2. Créer un nouveau projet Xcode"
echo "mkdir -p Frontend/TradingApp.xcodeproj"
echo "(Ou créez-le via l'interface Xcode: File → New → Project → macOS App)"
echo ""
echo "# 3. Configuration manuelle dans Xcode (Build Settings):"
echo "   HEADER_SEARCH_PATHS = \$(SRCROOT)/../../Backend/Include"
echo "   LIBRARY_SEARCH_PATHS = \$(SRCROOT)/../../Backend/build/lib"
echo "   OTHER_LDFLAGS = -lTradingBackend"
echo ""
echo "# 4. Ajouter Copy Files Phase:"
echo "   Product → Add Build Phase → New Copy Files Phase"
echo "   Destination: Frameworks"
echo "   Ajoutez: \$(SRCROOT)/../../Backend/build/lib/libTradingBackend.dylib"
echo ""
echo "📄 Fichiers Swift à ajouter au projet:"
echo "   - Frontend/TradingApp/ContentView.swift"
echo "   - Frontend/TradingApp/TradingViewModel.swift"
echo "   - Frontend/TradingApp/TradingBackend.swift"
echo "   - Frontend/TradingApp/TradingAppApp.swift"
echo ""
echo "⚠️ Important: Le nom de la librairie sur Mac est libTradingBackend.dylib"
echo "   (pas .so comme sur Linux)"
